### ISSUE TITLE
Some paths incorrectly contain double-slashes

### ISSUE THREAD

**Issue by BafDyce** [BafDyce/botamusique#32]
- Not a major bug but it's a bit annoying

**Comment by fsteffek** [comment]
Does this happen in the web interface, in the mumble client or both?

**Comment by BafDyce** [comment]
Both. I think the faulty code is in the `Dir()` object in `util.py`.

**Comment by BafDyce** [comment]
I am tackling this now. Looks like this only happens for the queue when adding an entire folder (recursively or not doesn't matter).
