### ISSUE TITLE
Register bot on mumble server to save server settings

### ISSUE THREAD

**Issue by fsteffek** [BafDyce/botamusique#35]
For the bot to be registered on the mumble server it needs a client certificate. 

On hold until #17 is fixed.

**Comment by BafDyce** [comment]
This is not an issue of the application but something how the application is used. --> Closed.

**Comment by fsteffek** [comment]
Yes, you're right, @BafDyce. For anyone wanting to register the bot, you will need a client certificate. AFAIK it's not implemented yet. See #17 for more information.
