### ISSUE TITLE
Implement a REST interface

### ISSUE THREAD

**Issue by fsteffek** [BafDyce/botamusique#38]

**Comment by BafDyce** [comment]
Closing this. It is just logical that we need to use the rest interface in the same moment as we build it. Otherwise we would have a broken application in between.

**Comment by fsteffek** [comment]
~I'm sorry it isn't really logical to me at the moment. Is it not possible to develop a rest interface separate from the current system? F.e. `GET https://example.com/rest` and `POST https://example.com/rest`.~

Oh, wait. It makes sense now. You would need second set of html forms. I believe it is possible, but it might not be a viable option.
